### ISSUE TITLE
error when filename contains [hash], [chunkhash] or [contenthash]

### ISSUE THREAD

**Issue by nilzona** [single-spa/single-spa-css#5]
if the webpack config is the following:
```js
module.exports = {
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].[contenthash].css",
    }),
    new ExposeRuntimeCssAssetsPlugin({
      // The filename here must match the filename for the MiniCssExtractPlugin
      filename: "[name].[contenthash].css",
    }),
  ],
};
```
the webpacked code tries to request a file where it seems [contenthash] has resolved to undefined

**Comment by joeldenning** [comment]
Thanks for reporting this issue, could you clarify which function is accessed that doesn't exist? Full stacktrace would be helpful.

**Comment by nilzona** [comment]
@joeldenning  yes, of course
My description was a bit wrong, if [contenthash] or [chunkhash] is used in the filename like the example above the request resolves to `thename.undefined.css` 
<img width="567" alt="Screenshot 2021-02-10 at 20 46 56" src="https://user-images.githubusercontent.com/2686595/107563302-30794680-6be1-11eb-9119-6b9e6d267a69.png">

I put together a sample repo here https://github.com/nilzona/sspa-react  that could be used to reproduce the issue

**Comment by joeldenning** [comment]
Thanks for providing the demonstration repo, I've put together a fix in #6 and released it in https://github.com/single-spa/single-spa-css/releases/tag/v1.1.2

**Comment by PieterBoeren** [comment]
Is this actually fixed?

In my compiled code I see:
```javascript

d.miniCssF = function(t) {
return "main.af8b913bd3008a4bad58.css"
   }, d.cssAssetFileName = function(t) {
  return (179 === t ? "main" : t) + "." + {
  179: "af8b913bd3008a4bad58"
   } [t] + ".css"
`

But the developer tools of the browsers shows me:

![image](https://user-images.githubusercontent.com/43775697/130237449-97e1db4a-a504-4f5c-a1fe-909bac456625.png)

**Comment by joeldenning** [comment]
If there's still a bug, please open a new issue with a demonstration.

**Comment by PieterBoeren** [comment]
Created #11.
