### ISSUE TITLE
Support link attributes like `crossorigin`?

### ISSUE THREAD

**Issue by miusuncle** [single-spa/single-spa-css#9]

**Comment by joeldenning** [comment]
Yeah I'm open to this. Maybe the best way would be the following?

```js
const lifecycles = singleSpaCss({
  createLink(url) {
    const linkEl = document.createElement('link')
    linkEl.rel = 'stylesheet'
    linkEl.crossOrigin = 'use-credentials'
    linkEl.href = url
    return linkEl
  }
})
```

The `createLink` option would allow full control over the link tag. Would you be open to sending in a pull request contributing this to single-spa-css?

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-css/releases/tag/v1.2.0

**Comment by joeldenning** [comment]
Documeted in https://github.com/single-spa/single-spa.js.org/pull/476
